-- checking counting records per tables ---
DROP PROCEDURE IF EXISTS `report_schema_count_rows`;
DELIMITER $$
CREATE PROCEDURE `report_schema_count_rows`(p_schema_name varchar(128))
BEGIN
DECLARE done INT DEFAULT 0;
DECLARE TNAME CHAR(255);
DECLARE table_names CURSOR for
    SELECT CONCAT("`", TABLE_SCHEMA, "`.`", table_name, "`") FROM INFORMATION_SCHEMA.TABLES where TABLE_TYPE = 'BASE TABLE' and TABLE_SCHEMA = p_schema_name;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
OPEN table_names;

DROP TABLE IF EXISTS TABLES_ROWS_COUNTS;
CREATE TEMPORARY TABLE TABLES_ROWS_COUNTS
  (
    TABLE_NAME CHAR(255),
    RECORD_COUNT INT
  ) ENGINE = MEMORY;

WHILE done = 0 DO
  FETCH NEXT FROM table_names INTO TNAME;
   IF done = 0 THEN
    SET @SQL_TXT = CONCAT("INSERT INTO TABLES_ROWS_COUNTS(SELECT '" , REPLACE(TNAME,"`","")  , "' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM ", TNAME, ")");

    PREPARE stmt_name FROM @SQL_TXT;
    EXECUTE stmt_name;
    DEALLOCATE PREPARE stmt_name;
  END IF;
END WHILE;
CLOSE table_names;

SELECT TABLE_NAME, RECORD_COUNT FROM TABLES_ROWS_COUNTS order by RECORD_COUNT desc;
SELECT SUM(RECORD_COUNT) AS TOTAL_DATABASE_RECORD_CT FROM TABLES_ROWS_COUNTS;

END$$
DELIMITER ;
